services:
  db:
    image: mysql:5.7
    container_name: wp-db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      wp-net:
        ipv4_address: 10.50.0.10

  wordpress:
    image: wordpress:latest
    container_name: wp-web
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: 10.50.0.10:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "8080:80"
    volumes:
      - web-volume:/var/www/html
    networks:
      wp-net:
        ipv4_address: 10.50.0.20

volumes:
  mysql-volume:
  web-volume:

networks:
  wp-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.50.0.0/24
