---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-backend
  annotations:
    pv.kubernetes.io/provisioned-by: kubevirt.io.hostpath-provisioner
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: crc-csi-hostpath-provisioner
  volumeMode: Filesystem
  csi:
    driver: kubevirt.io.hostpath-provisioner
    volumeHandle: pv-backend
    volumeAttributes:
      csi.storage.k8s.io/pv/name: pv-backend
      storagePool: local
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.hostpath.csi/node
              operator: In
              values:
                - crc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-frontend
  annotations:
    pv.kubernetes.io/provisioned-by: kubevirt.io.hostpath-provisioner
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: crc-csi-hostpath-provisioner
  volumeMode: Filesystem
  csi:
    driver: kubevirt.io.hostpath-provisioner
    volumeHandle: pv-frontend
    volumeAttributes:
      csi.storage.k8s.io/pv/name: pv-frontend
      storagePool: local
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.hostpath.csi/node
              operator: In
              values:
                - crc
