---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: crc-csi-hostpath-provisioner
  volumeName: pv-backend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-frontend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: crc-csi-hostpath-provisioner
  volumeName: pv-frontend
